#pragma once

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define FIRMWARE_MAJOR_VERSION 0
#define FIRMWARE_MINOR_VERSION 2
#define FIRMWARE_PATCH_VERSION 0

#define FIRMWARE_VERSION_LABEL ""

#define FIRMWARE_VERSION STR(FIRMWARE_MAJOR_VERSION) "." STR(FIRMWARE_MINOR_VERSION) "." STR(FIRMWARE_PATCH_VERSION) "-" FIRMWARE_VERSION_LABEL

#define FIRMWARE_VERSION_NUMBER (FIRMWARE_MAJOR_VERSION * 100 * 100 | FIRMWARE_MINOR_VERSION * 100 | FIRMWARE_PATCH_VERSION)